# Generated by Django 2.1.2 on 2019-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_dialog',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
