# Generated by Django 2.1.2 on 2019-03-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_dialog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active_dialog',
            new_name='dialog_id',
        ),
    ]
