# Generated by Django 2.1.2 on 2019-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190328_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language_code',
        ),
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
