# Generated by Django 2.1.2 on 2019-03-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190328_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
