# Generated by Django 2.2 on 2019-04-29 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('files', models.CharField(blank=True, max_length=40, null=True)),
                ('images', models.CharField(blank=True, max_length=40, null=True)),
                ('videos', models.CharField(blank=True, max_length=40, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_messages', to='member.Command')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
