# Generated by Django 2.2 on 2019-04-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_commandmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='text',
            new_name='caller',
        ),
        migrations.AddField(
            model_name='commandmessage',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('FILES', 'FILES'), ('IMAGES', 'IMAGES'), ('VIDEOS', 'VIDEOS')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
