# Generated by Django 2.2 on 2019-04-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20190429_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='content',
        ),
        migrations.AddField(
            model_name='commandmessage',
            name='text_length',
            field=models.IntegerField(default=0),
        ),
    ]
