# Generated by Django 2.2 on 2019-05-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20190429_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='amswer_preview',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('EDIT_CALLER', 'EDIT_CALLER'), ('EDIT_ANSWER', 'EDIT_ANSWER')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
