# Generated by Django 2.2 on 2019-05-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20190502_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandmessage',
            name='audios',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
