# Generated by Django 2.2 on 2019-05-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_commandmessage_audios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandmessage',
            name='audios',
        ),
        migrations.RemoveField(
            model_name='commandmessage',
            name='files',
        ),
        migrations.RemoveField(
            model_name='commandmessage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='commandmessage',
            name='text_length',
        ),
        migrations.RemoveField(
            model_name='commandmessage',
            name='videos',
        ),
        migrations.AddField(
            model_name='commandmessage',
            name='file_list',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandmessage',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('PHOTO', 'PHOTO'), ('DOCUMENT', 'DOCUMENT'), ('VIDEO', 'VIDEO'), ('AUDIO', 'AUDIO'), ('VOICE', 'VOICE'), ('LOCATION', 'LOCATION')], max_length=20),
        ),
    ]
