# Generated by Django 2.2 on 2019-05-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20190507_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandmessage',
            old_name='file_list',
            new_name='file_id',
        ),
    ]
