# Generated by Django 2.2 on 2019-05-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20190508_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='amswer_preview',
        ),
    ]
