# Generated by Django 2.2 on 2019-05-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_errorreport_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botadmin',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_set', to='member.Bot'),
        ),
        migrations.AlterField(
            model_name='botadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_set', to='main.User'),
        ),
        migrations.AlterField(
            model_name='command',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_set', to='member.Bot'),
        ),
        migrations.AlterField(
            model_name='commandmessage',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_set', to='member.Command'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_set', to='member.Bot'),
        ),
    ]
