# Generated by Django 2.2 on 2019-04-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='full_username',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='username',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
