# Generated by Django 2.2 on 2019-04-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190408_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='full_username',
        ),
    ]
