# Generated by Django 2.2 on 2019-04-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_faqrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='negative_count',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='positive_count',
        ),
    ]
