# Generated by Django 2.2 on 2019-04-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190412_0923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
