# Generated by Django 2.1.7 on 2019-03-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='name',
            field=models.CharField(default='Name', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_user', to='accounts.User'),
        ),
    ]
