# Generated by Django 2.1.7 on 2019-03-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20190330_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_set', to='accounts.User'),
        ),
    ]
